fix(check): add missing module
Test was failing with

```
    error: The option `system.image.updates' does not exist. Definition values:
       - In `/nix/store/ylp7g3dmsqgg2m3qvlr8m91vp2rs15pq-source/tests/common.nix':
           {
             url = "http://server.test/";
           }
```

It runs now but the update test still fails, but I guess that is a setup
problem.